version: '3'
services:
  app:
    build: .
    environment:
      DB_HOST: database
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
    ports:
    - "5432:5432"